### ISSUE TITLE
Структура

### ISSUE THREAD

**Issue by FanManutd** [Rizarid/apartmen-seach#1]
### Blocks and components

Чем папка blocks отличается от components? Если мы смотрим с точки зрения БЭМ, в обоих папках лежат блоки. Нет смысла делить на низкоуровневые блоки и блоки, которые подключают другие блоки. Максимум, что я видел, люди по разному называют папки. Кто-то components, кто-то blocks. Как тебе нравится. 
![image](https://user-images.githubusercontent.com/90761929/134666947-daa2bfa8-3a31-4a71-81af-9b50875b6fd7.png)

### Scripts
Функции, которые хранятся в папке scripts, по сути являются утилитами. Поэтому лучше их вынести в один файл, например utils.js. Папку тоже можно переименовать. 
![image](https://user-images.githubusercontent.com/90761929/134669105-988b0648-6b1a-423c-bddc-794247702438.png)

**Comment by Rizarid** [comment]
> Чем папка blocks отличается от components? Если мы смотрим с точки зрения БЭМ, в обоих папках лежат блоки. Нет смысла делить на низкоуровневые блоки и блоки, которые подключают другие блоки. Максимум, что я видел, люди по разному называют папки. Кто-то components, кто-то blocks. Как тебе нравится.

С точки зрения БЭМ смысла в этом нет, зато с точки зрения удобства работы над проектом есть. Когда все не перемешано в одной папке, гораздо проще и быстрее искать нужное и перемещаться между компонентами. И БЭМ по мойму этого на прямую не запрещает.

**Comment by FanManutd** [comment]
> Когда все не перемешано в одной папке, гораздо проще и быстрее искать нужное и перемещаться между компонентами. 

Пока можно оставить)

**Comment by Rizarid** [comment]
Исправил

**Comment by FanManutd** [comment]
Точно ли стоит тащить вот это:
![image](https://user-images.githubusercontent.com/90761929/135074157-11a7c4d7-b751-4476-b12e-522bc41c87ac.png)

ради 3х иконок:
![image](https://user-images.githubusercontent.com/90761929/135074212-3ab64cac-48b2-4a42-800b-e7dd200e5da0.png)

?

**Comment by FanManutd** [comment]
### Import sass files

Sass поддерживает импорт файлов. Нет необходимости создавать js - файл только для того, что бы импортить стили. Если хочешь, можно сделать так, что бы вебпак автоматически собирал все стили (уже в js), тогда не нужно будет их вообще импортить (кроме переменных). Но это на твоё усмотрение, с меня например потребовали автоимпорт стилей, я не буду)

**Comment by Rizarid** [comment]
> Sass поддерживает импорт файлов. Нет необходимости создавать js - файл только для того, что бы импортить стили.

А чем эти js файлы мешают? Мне кажется гораздо удобнее, вместо 3-ех цепочек импортов вести только 2.

> Если хочешь, можно сделать так, что бы вебпак автоматически собирал все стили (уже в js), тогда не нужно будет их вообще импортить (кроме переменных). Но это на твоё усмотрение, с меня например потребовали автоимпорт стилей, я не буду)

Мне не нравится автоимпорт тем, что он собирает именно **все стили**  всех страниц, что существенно утяжеляет итоговый файл стилей и следовательно замедляет загрузку страницы.

**Comment by FanManutd** [comment]
Окей, не критично как по мне.
