### ISSUE TITLE
Build errors 

### ISSUE THREAD

**Issue by Feinminen** [Rizarid/apartmen-seach#14]
Сейчас если заново склонировать проект, установить зависимости и стартануть - он не соберётся нормально из-за проблем с путями.
Крайне вероятно, проблема появилась из-за того что ты менял регистр файлов локально, но гит изначально регистронезависимый и только изменения регистра файла он не подхватывает, отсюда и проблемы.
![image](https://user-images.githubusercontent.com/44312820/151004668-09ce14a5-8bde-4037-89d6-8506109aad9a.png)

**Comment by Rizarid** [comment]
После последних обновлений склонировал проект. У меня все успешно установилось.

**Comment by Feinminen** [comment]
Я не совсем понимаю как это возможно, даже если сейчас репу на ГХ посмотреть, то явно видно, что пути не будут резолвится из-за различий в регистре
![image](https://user-images.githubusercontent.com/44312820/152649707-1b49b9b8-0d99-458f-9309-68f67a036404.png)
![image](https://user-images.githubusercontent.com/44312820/152649730-bd4e8b5f-a5c4-4f13-888c-f314ed8a6960.png)

**Comment by Rizarid** [comment]
Действительно странно... Но оно как-то собирается:

![image](https://user-images.githubusercontent.com/60002712/152683950-68abe6cb-bcb3-444f-87d4-73231d55e287.png)

![image](https://user-images.githubusercontent.com/60002712/152684069-7de4a6d0-4d47-4270-997b-9fdc26b781ae.png)

Я перезаписал эти шрифты с новым регистром, так что теперь должно работать.
