### ISSUE TITLE
Minor UI/UX issues

### ISSUE THREAD

**Issue by Feinminen** [Rizarid/apartmen-seach#16]
На ховер у не закрашенной кнопки меняется прозрачность только бордера:
![image](https://user-images.githubusercontent.com/44312820/151006689-924ee671-a4ce-454c-beb7-30143a9f3de9.png)

Весь айем дропдауна должен быть интерактивным, не только текст:
![image](https://user-images.githubusercontent.com/44312820/151008222-4aacdc4f-81db-4d3a-b079-59dde155909d.png)

У меня почему-то переодически на клик не закрывается вот этот дропдаун, со всеми остальными ок, как будто событие не всплывает до обработчика порой:
![image](https://user-images.githubusercontent.com/44312820/151008945-e949b33a-09ba-43e2-b814-9b709060489c.png)

У дропдауна разделитель между инпутом и элемнетами в дизайне в один пиксель - у тебя в два:
![image](https://user-images.githubusercontent.com/44312820/151009229-a093ffcf-6df9-4264-9eb0-cdb7f32241f6.png)
![image](https://user-images.githubusercontent.com/44312820/151009297-e8de0a04-be72-4be3-afcc-7b9ebd981512.png)

Ещё увидел вот такой забавный баг, при изменении инпута почему-то меняет расположение обводка:
![shakeitbaby](https://user-images.githubusercontent.com/44312820/151009582-768981fa-6d3b-48d0-b984-b354016389ef.gif)

Есть ещё минорные расхождения с PP, но их поправить надо, т.к. верстаться должно было именно по PP:
![image](https://user-images.githubusercontent.com/44312820/151010171-bff99ec5-543c-4838-b87c-bfa9e7587b98.png)

![image](https://user-images.githubusercontent.com/44312820/151010237-6d8fb5a8-7a9c-40f2-af09-7a966c0aa872.png)

![image](https://user-images.githubusercontent.com/44312820/151010708-b7a58367-4053-4aa6-a8d9-6b90200d76b7.png)

Тут другой цвет текста:
![image](https://user-images.githubusercontent.com/44312820/151011017-b2a13a01-cadd-4918-b115-36a25924af3d.png)

![image](https://user-images.githubusercontent.com/44312820/151011128-7b652a1b-3faa-49d0-945b-7c4a36752a3d.png)

![image](https://user-images.githubusercontent.com/44312820/151011477-59616d68-f387-4018-a19f-093ddee62597.png)

Предполагалось, что вот эти элементы интерактивные:
![image](https://user-images.githubusercontent.com/44312820/151012712-8d745639-d4b9-40a9-a6d7-8160d2ed69cd.png)
На пагинацию можно менять страницу соответсвенно, а на rating менять количество звездочек

**Comment by Rizarid** [comment]
> На ховер у не закрашенной кнопки меняется прозрачность только бордера:

А эта проблема в каком браузере выплывает? Я проверил в chrome, firefox и edge и во всех прозрачность текста при наведении меняется:

![image](https://user-images.githubusercontent.com/60002712/151151428-2f5c6b7e-a5d7-48ba-a018-97fbaf3cd971.png)
![image](https://user-images.githubusercontent.com/60002712/151151441-209b02b1-235f-429f-8291-d5cf75b33e18.png)

**Comment by Feinminen** [comment]
Это правильное поведение как раз, прошу прощения, мальца криво описал :)
Так в макете нарисовано (с изменением прозрачности только бордера).
https://github.com/Rizarid/apartmen-seach/issues/16#issuecomment-1022089297
