### ISSUE TITLE
Social links

### ISSUE THREAD

**Issue by Feinminen** [Rizarid/apartmen-seach#17]
Эти линки должны вести на странички соц сетей и должны быть выполнены по [стнадартам](https://github.com/fullstack-development/front-end-best-practices/blob/ba62e2aac84e0845a504f323a7e868cb0cef202f/HTML/README.md#2.12)
![image](https://user-images.githubusercontent.com/44312820/151012837-ee9c0a37-9f26-4f84-a5d8-4e6bf839ba42.png)

**Comment by Feinminen** [comment]
Сейчас получается так, что пути не на внешние ресурсы, а стандарты для внешних.
Просто измени пути на пути до главных страниц твиттера, фб и инсты соответсвенно :)

**Comment by Rizarid** [comment]
Исправил
