### ISSUE TITLE
Дефолтные опции для миксинов

### ISSUE THREAD

**Issue by Feinminen** [Rizarid/apartmen-seach#18]
Сейчас есть много миксинов, куда прокидывается путой объект, чтобы были дефолтные опции.
Чтобы этого избежать можно просто по дефолту давать передавать параметрам пустой объект
![image](https://user-images.githubusercontent.com/44312820/152652886-3d608695-b751-4c3c-a99b-1c00d3d8fc28.png)

**Comment by Rizarid** [comment]
Исправил
