### ISSUE TITLE
Excess JS usage 

### ISSUE THREAD

**Issue by Feinminen** [Rizarid/apartmen-seach#19]
Сейчас у очень многих компонентов JS по факту ничего не делает кроме того что прокидывает нужный класс в нужные блоки. 
![image](https://user-images.githubusercontent.com/44312820/152653405-2f6cdb53-2260-4bea-9d66-9565cc1a122a.png)
Любой блок, который содержит JS, при инициализации блока сразу же должен стать рабочим.
 ```+dateDropdown()``` сразу должен дать рабочий код с дефолтными параметрами, без танцев с бубнами

Если у нас будет кейс, когда мы должны добавить 50 карточек, которые работают с JS-ом в разных местах, мы же не будем в 50 разных мест вызывать один и тот же код.

Мы можем просто найти все компоненты с каким-то конкретным классом и для каждого найденного элемента заинитить свой экземпляр. И тогда как раз у тебя не будет внутренних зависимостей одного блока на другой.
Примерно следующим образом:
![image](https://user-images.githubusercontent.com/44312820/152653546-b9e7b1ab-b180-43f1-a376-43dcc9c7e978.png)

И тогда уйдёт большая половина JS-a из проекта :)

**Comment by Rizarid** [comment]
1. Такой вариант нарушает инкапсуляцию компонента.
2. Он будет работать сильно медленнее, так как для инициализации каждого компонента, необходимо обойти все дерево документа. То есть  если у нас 50 компонентов для изначальной инициализации страницы нужно 50 раз произвести поиск по всему документу, что является довольно дорогой операцией.
3. И я этот момент, начиная с пред ревью, туда обратно уже 2 раза переписывал может хватит уже?  https://github.com/Rizarid/apartmen-seach/issues/5

**Comment by Feinminen** [comment]
/irony/
![image](https://user-images.githubusercontent.com/44312820/152698204-9e9d1b78-fb54-4557-a799-f1850ee1c450.png)

:D

**Comment by Feinminen** [comment]
> * Такой вариант нарушает инкапсуляцию компонента.
> * Он будет работать сильно медленнее, так как для инициализации каждого компонента, необходимо обойти все дерево документа. То есть  если у нас 50 компонентов для изначальной инициализации страницы нужно 50 раз произвести поиск по всему документу, что является довольно дорогой операцией.
> * И я этот момент, начиная с пред ревью, туда обратно уже 2 раза переписывал может хватит уже?  [JS #5](https://github.com/Rizarid/apartmen-seach/issues/5)

1. Не понимаю каким образом нарушается инкапсуляция компонента. Возможно я что-то не досмотрел, но в том варианте который я описал компонент кроме как от себя не от чего не зависит.
Его можно конфигурировать через миксин, но при этом вся логика как раз сокрыта внутри и на неё ничего извне никак не влияет (если мы передали кривой рут элемент, то мы сами виноваты, в твоей имплементации тоже можно так накосячить). Можешь пояснить что ты имеешь ввиду под нарушением инкапсуляции?
2. Нужно произвести поиск всего 1 раз, просто найдутся все 50 элементов сразу и мы их сразу заинитим, а вот в твоём случае мы как раз при каждой инициализации искали бы элемент в ДОМ дереве 
![image](https://user-images.githubusercontent.com/44312820/152698374-adf480e5-bbd4-43dc-9c78-f1c57f76c02f.png)

50 инициализаций - 50 поисков по дому и так с каждым элементом.

3. Да, бывает и такое, но мне кажется там все равно была не такая же реализация как я описал и проблема была в несколько другом. Сейчас покопаюсь в истории гита, если действительно заставили переписывать с варианта, который я описал, то, думаю, можешь оставить как есть. Но в любом случае ответь на два верхних пункта, пожалуйста. UPDATE: замечание предыдущего ревьюера было в том, что у тебя инициализировались любые JS файлы КАЖДЫЙ раз когда они использовались(т.е. если в трёх блоках был дропдаун, то мы трижды для одного и того же элемента инициализировали класс), это можно делать единожды для всего приложения. 

ПЫСЫ, я могу что-то упускать, т.к. зачастую скимлю код, так что я не настаиваю на своей правоте, но надо объяснить свою точку зрения. В чем плюс именно такой имплементации

**Comment by Feinminen** [comment]
P.S по таким вопросам(где надо именно обсудить что-то) можешь писать в телеграм, я там быстрее отвечать буду

**Comment by Rizarid** [comment]
> 1. Не понимаю каким образом нарушается инкапсуляция компонента. Возможно я что-то не досмотрел, но в том варианте который я описал компонент кроме как от себя не от чего не зависит.
>    Его можно конфигурировать через миксин, но при этом вся логика как раз сокрыта внутри и на неё ничего извне никак не влияет (если мы передали кривой рут элемент, то мы сами виноваты, в твоей имплементации тоже можно так накосячить). Можешь пояснить что ты имеешь ввиду под нарушением инкапсуляции?

В твоем описании не понятно где именно должен происходить этот поиск. Если поиск производит родительский компонент или напрямую на странице то откуда внешний компонент знает подробности реализации дочернего компонента (имеется в виду название его класса по которому происходит поиск). Таким образом если я захочу изменить реализацию дочернего компонента, изменив название его класса, то мне придется вносить изменения во все компоненты в которых измененный компонент подключается. Следовательно существует прямая зависимость родительского компонента от внутренней реализации дочернего компонента и значит инкапсуляция  дочернего компонента нарушена.
Если же подразумевалось, что компонент по сути состоит из двух js файлов, в одном класс, а в другом как раз поиск компонентов и инициализация  экземпляров класса (примерно так как ты и написал в своем примере кода). И в родительском компоненте просто подключается файл с инициализацией.  В таком случаи инкапсуляция действительно не нарушается, но у этого подхода есть свои проблемы, которые и поднимались в issue #5. Есть компоненты которые используются не в одном блоке, а в нескольких блоках на одной и той же странице, и при подключении этих блоков будет происходить повторный поиск и инициализация этих повторяющихся компонентов.

В моем же варианте родительский компонент просто передает дочернему при инициализации элемент внутри которого следует производить локальный поиск дочернего компонента, и ему безразличны изменения внутри дочернего компонента если они не касаются конкретно параметров инициализации. Аналогично в коде дочернего компонента нет привязки к конкретному родителю, он принимает ссылку на элемент и ищет свой класс в нем. Поскольку поиск ограничивается переданным елементом, также не происходит повторной инициализации одинаковых компонентов на странице.

**Comment by Rizarid** [comment]
> 2\. Нужно произвести поиск всего 1 раз, просто найдутся все 50 элементов сразу и мы их сразу заинитим, а вот в твоём случае мы как раз при каждой инициализации искали бы элемент в ДОМ дереве
>     ![image](https://user-images.githubusercontent.com/44312820/152698374-adf480e5-bbd4-43dc-9c78-f1c57f76c02f.png)
> 
> 50 инициализаций - 50 поисков по дому и так с каждым элементом.

Да для одинаковых компонентов поиск производится один раз (кроме варианта указанного выше). Но для каждого уникального компонента производится полный обход дерева. Т.е. для инициализации компонента dateDropdown нужно сделать полный обход дерева, затем для инициализации компонента dropdown нужно снова обойти все дерево, для инициализации кнопок, нужно снова обойти все дерево и т.д. 
В моей же реализации полного обхода дерева не происходит. Класс страницы ищет  внутри себя контейнеры блоков. Затем инициализирует блоки передавая ему его родительский элемент. Дальше блок ищет себя локально в родительском элементе. Так как используется querySelector а не querySelectorAll, то поиск происходит до первого встреченного совподения, а искомый элемент является первым дочерним, поиск по сути и начаться то не успевает. дальше блок, локально внутри себя ищет контейнеры компонентов  и инициализирует их. Да количество запросов на поиск при таком подходе получается больше, но за счет того что локальный поиск сильно быстрее перебора всего дерева, то он все равно работает быстрее.
Разница в скорости загрузки страницы, между данными подходами, возрастает с увеличением количества уникальных компонентов на странице. Я реализовывал оба варианта и если для главной страницы разницы почти не было, то для страницы поиска  номеров, разница уже была очень существенная.

**Comment by Rizarid** [comment]
> 3\. Да, бывает и такое, но мне кажется там все равно была не такая же реализация как я описал и проблема была в несколько другом. Сейчас покопаюсь в истории гита, если действительно заставили переписывать с варианта, который я описал, то, думаю, можешь оставить как есть. Но в любом случае ответь на два верхних пункта, пожалуйста. UPDATE: замечание предыдущего ревьюера было в том, что у тебя инициализировались любые JS файлы КАЖДЫЙ раз когда они использовались(т.е. если в трёх блоках был дропдаун, то мы трижды для одного и того же элемента инициализировали класс), это можно делать единожды для всего приложения.

Подключать все мелкие компоненты напрямую на страницу не особо удобно. Скажем если мне нужно убрать со страницы обин блк и заменить его на другой, мне нужно найти и убрать все дочерние компоненты первого блока, затем добавить все дочерние элементы нового блока. Да и разница в скорости загрузки страницы (о которой я писал выше) никуда не денется.
Если же подключать все компоненты проекта к каждой странице, то количество обходов дерева будет ровняться уже не количеству уникальных компонентов на конкретной странице, а количеству уникальных компонентов в проекте, не важно используется он на данной странице или же нет. Что еще сильнее снизит скорость загрузки страницы.
