### ISSUE TITLE
Pug

### ISSUE THREAD

**Issue by FanManutd** [Rizarid/apartmen-seach#2]
### Аргументы
Options, получаемые в миксине, можно сразу деструктурировать в аргументах миксина. Так будет сразу видно, какие опции принимает миксин. 
![image](https://user-images.githubusercontent.com/90761929/134670512-16f15c80-bb67-4145-bce7-1cbe74d87d52.png)

### Unescaped Buffered Code
Разве этот синтаксис не излишний? Есть причина по которой это используется повсеместно? 
![image](https://user-images.githubusercontent.com/90761929/134671080-f32ebff5-fa2d-43d3-85f4-9221173cf5e7.png)

**Comment by Rizarid** [comment]
> Options, получаемые в миксине, можно сразу деструктурировать в аргументах миксина. Так будет сразу видно, какие опции принимает миксин.

В некоторых компонентах options, передаваемый в миксин, большой и не помещается в строку. Например:
![image](https://user-images.githubusercontent.com/60002712/134717436-d697eb89-a8ed-4a0f-930e-271a932531e3.png)
Если перенести строку  при объявлении аргументов миксина, то вылазит ошибка и ничего не компилится. 
![image](https://user-images.githubusercontent.com/60002712/134718177-fbf950e5-dbd0-4be5-b1f4-1d714fb5f2d9.png)
![image](https://user-images.githubusercontent.com/60002712/134718346-5c8f0515-00ec-4af4-8502-64a93bbadb97.png)
Поэтому я начал выносить деконструкцию уже под объявление миксина. И затем, в других местах, вынес для соблюдения единообразия кода. 
Но, если это сильно ухудшает читаемость кода, то где возможно я перенесу в объявление миксина.

**Comment by FanManutd** [comment]
> В некоторых компонентах options, передаваемый в миксин, большой и не помещается в строку.
Если перенести строку при объявлении аргументов миксина, то вылазит ошибка и ничего не компилится.

Да, действительно это так и это проблема pug. И да, иногда придётся проскролить вправо, что бы дочитать аргументы. Это нормально для pug. В дальнейшем такого не будет. Но для читаемости, лучше всё таки деструктурировать в аргументах миксина, даже если аргументы длинные.

**Comment by Rizarid** [comment]
Исправлено

**Comment by FanManutd** [comment]
> Разве этот синтаксис не излишний? 

В одном файле осталось
![image](https://user-images.githubusercontent.com/90761929/135057756-08bc6ea0-4540-4b0f-b528-da097b0dc7a6.png)

**Comment by Rizarid** [comment]
Поправил

**Comment by FanManutd** [comment]
### Именование

Смотри, у тебя папка booking-block, миксин bookingBlock, в котором находится БЭМ блок booking. И JS класс называется Booking. И таких мест много. Название папок, файлов и БЭМ блоков должны быть block-name, названия js-классов в BlockName. Названия миксинов на твоё усмотрение. На всякий случай паг поддерживает block-name.
![image](https://user-images.githubusercontent.com/90761929/135485335-a2567364-8f18-43fd-944b-93f33133d16f.png)

### Тег section

Ты местами неправильно применяешь тег `section`. Тег `section` должен выделять на странице какой-то большой смысловой блок или раздел. Надо в некоторых местах убрать.
![image](https://user-images.githubusercontent.com/90761929/135481635-8a2b8b59-00e3-4d7f-91bf-26092d473794.png) 

### Button

Кнопка должна быть тегом `button` или инпутом с `type="button"`
![image](https://user-images.githubusercontent.com/90761929/135479998-d72bbdce-d7d0-4cab-ba3f-66e52c9dd26e.png)

### Checkbox

Некорректный компонент. Получается у тебя чекбокс без label, не самостоятельный, ты оборачиваешь его в label в другом месте. 
![image](https://user-images.githubusercontent.com/90761929/135480615-3bdbc348-5266-4fd2-b0d4-8081a9fd995b.png)

### Pagination 

Пустые span?
![image](https://user-images.githubusercontent.com/90761929/135486584-728966e2-3fed-493d-8be8-b17b98a93698.png)

**Comment by FanManutd** [comment]
Можно сразу использовать `const`:
![image](https://user-images.githubusercontent.com/90761929/135854138-8ebbce0b-8ea7-47bd-93d2-cd70931da74d.png)

Забыл один файлик
![image](https://user-images.githubusercontent.com/90761929/135856433-3fe84cea-5fb6-45bd-af57-e7ac0888a96d.png)

**Comment by Rizarid** [comment]
> Можно сразу использовать `const`

Здесь мне нужно изолировать импортируемый numberMargins, так как если на страницу подключается два компонента с одинаковым импортом, то сборка сломается (ну или его нужно переименовывать). Поскольку, придумывать в каждом компоненте, свое имя для одной и той же функции, мне кажется плохой идеей, я решил импортировать в область с отдельной областью видимости. Но если объявить константы в нейже, то я не смогу потом их использовать на странице.

**Comment by FanManutd** [comment]
> Здесь мне нужно изолировать импортируемый numberMargins, так как если на страницу подключается два компонента с одинаковым импортом, то сборка сломается (ну или его нужно переименовывать).

Окей.

Тут внешнее позиционирование блока затесалось, так делать нельзя)
![image](https://user-images.githubusercontent.com/90761929/135860625-a0cc3d47-4814-4759-bb6b-4d1fef0f4b4e.png)
