### ISSUE TITLE
Minor BEM issues

### ISSUE THREAD

**Issue by Feinminen** [Rizarid/apartmen-seach#20]
Именование не по БЭМ, нашёл только тут, но возможно где-то ещё осталось:
![image](https://user-images.githubusercontent.com/44312820/152654099-67d85707-e10a-45e2-9b2d-f676e1d42b19.png)

В БЭМ есть два вида модификаторов, булевы и ключ значение. Булевы, это когда у модификатора может быть только булево значение true/false, например withPadding/disabled/focused и прочее, значение либо тру либо фолс.
Синтаксис у таки модификаторов следующий ```elem_booleanModifierValue```

А есть модификаторы ключ/значение, такие модификаторы должны иметь всегда один ключ, но могут иметь несколько значений вэлью и синтаксис следующий ```elem_key_value```
У тебя все модификаторы сейчас записаны по синтаксису как булевы, хотя многие из них таковыми не являются, как вот тут, например:
![image](https://user-images.githubusercontent.com/44312820/152654264-3af5f150-e0bd-4cdd-95d6-ed8b83d064ea.png)

Должно быть следующим образом:
![image](https://user-images.githubusercontent.com/44312820/152654292-fd66edad-125a-4130-9c7a-3c3bc229f49a.png)

По синтаксису сразу понятно, что у модификатора может быть несколько значений и что это за значения

**Comment by Rizarid** [comment]
исправил
