### ISSUE TITLE
Sass

### ISSUE THREAD

**Issue by FanManutd** [Rizarid/apartmen-seach#4]
Стили, как это ни странно прозвучит, написаны в разном стиле. Сначала я подумал, что ты упустил одно из главных преимуществ препроцессоров - избавиться от дублирования кода, как здесь: 
![image](https://user-images.githubusercontent.com/90761929/134673500-d7391b23-77f9-421e-a44a-c1776c76aa50.png)
Но потом наткнулся на такой sass, где всё хорошо, но почему-то снова затисалась запись вида `& .block__element`
![image](https://user-images.githubusercontent.com/90761929/134673847-9d449a9c-8639-454e-b4b8-6329db5a62c6.png)

Я отметил галочкой, какая запись является хорошей. Суть в том, что у тебя есть один блок `.block` и элементы этого блока, к которым можно обратиться через `&__element` внутри блока. Затем, внутри элемента(или блока) можно обратиться к модификатору `&_modifier`. Таким образом у нас исчезнет так называемая "лестница", которая присутствует на 1м скрине, которая в теории может разростись сильно вправо и сама по себе делает код менее читаемым.

**Comment by Rizarid** [comment]
При помощи такого синтаксиса я повышаю специфичность правил. Чтобы в конечном файле было не `.toggle .toggle__circle` а `.toggle .toggle__switch .toggle__circle`. Это делается для повышения надежности верстки при использовании широко распространенных наименований. Так должно совпасть больше деталей, чтобы переопределить верстку.

**Comment by FanManutd** [comment]
> При помощи такого синтаксиса я повышаю специфичность правил.

Одно из преимуществ БЭМ - создание пространства имён, которое не пересекается с другими блоками. Если мы определили блок `.toggle`, то элемент `.toggle__circle` может быть только внутри `.toggle`. Повышение специфичности правил является излишним. БЭМ это делает за нас. 

> Это делается для повышения надежности верстки при использовании широко распространенных наименований. Так должно совпасть больше деталей, чтобы переопределить верстку.

Мы же разрабатываем сайт, конечный продукт. Откуда на нашем сайте могут появится два блока с одинаковым названием? 
А если мы говорим о потенциальном подключении стороннего компонента, чьё название может совпадать с названием нашего компонента, то специфичность селекторов здесь может помочь лишь в малой степени (и то не факт). У нас всё равно на странице окажутся два разных блока `.toggle`. И какой тогда смысл от БЭМ? Если мы окажемся в такой ситуации, решать её придётся изменением именования, а не специфичностью селекторов.

**Comment by Rizarid** [comment]
Убедил, буду переделывать.

**Comment by Rizarid** [comment]
Исправил
