### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by FanManutd** [Rizarid/apartmen-seach#5]
### Переиспользуемость

Блоки должны быть независимы и переиспользуемы. Вот тут например, что будет, если я подключу два блока `booking-block` на страницу? (вопрос риторический) 
![image](https://user-images.githubusercontent.com/90761929/134677067-542f9885-8d6d-4a75-b7ee-c85b218a9522.png)

Твоё же решение, как на скриншоте ниже, не идеальное: 
![image](https://user-images.githubusercontent.com/90761929/134677894-16031131-d5c2-4d78-bc55-8439cab00ea2.png)

Что произойдёт, если например блок `boocking-block` подключить на страницу form-elements? В `booking-block` подключается `dropdown` и ищутся все `.js-dropdown` в `document`. На странице form-elements происходит тоже самое, подключается `dropdown` и ищутся все `.js-dropdown` в `document`. 
![image](https://user-images.githubusercontent.com/90761929/134678350-f244d7d3-2469-4fec-a907-350f95e97e91.png)
![image](https://user-images.githubusercontent.com/90761929/134678359-6f4fba75-6afc-4985-9010-8ff4e6af3dc4.png)

Получается экземпляры для каждого `dropdown` будут созданы как минимум два раза. А если ещё что нибудь подключить?) Нужно чуть чуть переосмыслить архитектуру.

**Comment by Rizarid** [comment]
Я знаю эти минусы. К перечисленным тобой минусам могу добавить и то, что придется перебрать все дерево столько раз, сколько у нас компонентов на странице, что сильно сказывается на скорости загрузки страницы. Однако это не мое решение. Прежде, у меня страницы инициализировали классы блоков, а те в свою очередь, инициализировали содержащиеся в них компоненты. Но на пред ревью мне сказали, что нужно инициализацию каждого компонента вынести в отдельный init.js, который должен лежать в папке компонента. Я собственно так и сделал.
Скрин из списка исправлений.
![image](https://user-images.githubusercontent.com/60002712/134687394-98fd5b52-1f63-4d73-ac62-2143e003bbfa.png)

**Comment by FanManutd** [comment]
Я посмотрел предыдущие коммиты и возможно докопался до сути. Вот например старый код страницы `cards`
![image](https://user-images.githubusercontent.com/90761929/134723605-666e80a7-8a16-4036-b6fa-15164b73e74d.png)
Откуда страница `cards` знает о внутренней реализации этих блоков? Откуда ей знать о классах `.js-room-card-block` или `js-search-block`? То есть ты как бы инициализиварол внутреннюю часть блока на странице `cards`. Возможно формулировка могла быть другой. Предыдущий ревьюер предложил вынести это в отдельный файл init, но главное - внутрь блока. 

В идеальном случае класс блока при создании экземпляра должен получать своего родителя, куда подключается этот блок. И уже внутри этого родителя искать все необходимые ему DOM-узлы. Что я собственно и предлагаю сделать. От файла init можно отказаться. Главное, что бы страница или блок, подключающий другие блоки, не знал о внутренней реализации подключаемого блока.

Например, страница `cards`. И нам нужно подключать `button`. Будет DOM-узел `.cards__button`. И при подключении блока `button`, передаваться будет `.cards__button`, внутри которого блок `button` будет находить всё что ему нужно. Приставки js- опущены для краткости.

**Comment by Rizarid** [comment]
Ок, так и сделаю. Только бы потом обратно переписывать не пришлось)

**Comment by Rizarid** [comment]
Исправил

**Comment by FanManutd** [comment]
Зачем копировать код плагинов к себе в проект? Плагин должен импортироваться из node_modules и работать. 
![image](https://user-images.githubusercontent.com/90761929/135073016-8e7bf220-ea71-47f9-a788-440fce50266e.png)

**Comment by Rizarid** [comment]
Исправил

**Comment by FanManutd** [comment]
> Плагин должен импортироваться из node_modules

ui-datepicker
![image](https://user-images.githubusercontent.com/90761929/135463389-5871ecf1-651c-4660-b99f-63b12d58f888.png)

**Comment by Rizarid** [comment]
> ui-datepicker

У этого дополнения нет npm версии.
