### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by FanManutd** [Rizarid/apartmen-seach#6]
### User select

У содержимого кликабельных элементов не должно быть возможности попадать в выделение.
![image](https://user-images.githubusercontent.com/90761929/135061024-9dbd135c-80fd-467d-aa56-35238468f401.png)

### Dropdown

Странное решение скрывать дропдаун, когда курсор покидает его. Так же дропдаун не закрывается по повторному нажатию на инпут или по нажатию за областью дропдауна. 
![dropdown](https://user-images.githubusercontent.com/90761929/135062955-3e69759d-95d5-485a-9762-29b46e357564.gif)

### Date dropdown

Календарь так же должен скрываться при повторном нажатии на инпут или за его пределами. 
![date](https://user-images.githubusercontent.com/90761929/135063948-19a94dd1-b870-4b92-b1dc-557f2bd97f67.gif)

### Content overflow

Текст выходит за элемент. 
![image](https://user-images.githubusercontent.com/90761929/135063861-cdfbdbc6-fac2-4910-912a-e672d1e31db1.png)

### Placeholder

Placeholder при фокусе не должен становиться одного цвета с текстом. 
![image](https://user-images.githubusercontent.com/90761929/135064763-2eafcef5-7c4f-4464-8523-15f5aaf9d529.png)

### Toggle

Это короткое исчезновение можно пофиксить. В крайнем случае подскажу как. 
![toggle](https://user-images.githubusercontent.com/90761929/135065793-0a8ebf08-5a96-485b-beaf-4edbdfa42d34.gif)

### Room card

Что бы такого не было(кривые кругляши), надо задавать целочисленные пиксели. В макете 7.5, можно 8 пикселей. 
![image](https://user-images.githubusercontent.com/90761929/135066619-13d4db77-f66f-4d8a-9067-76dbfacd3fb8.png)

**Comment by FanManutd** [comment]
### Header

1)Ссылки Шрёдингера ;) 
2)Пункты меню, где рядом есть стрелочка - это выпадающее меню, а не ссылка. Поэтому при клике на надпись "Соглашения" должен выпадать список, а не происходить переход по ссылке
![header](https://user-images.githubusercontent.com/90761929/135070568-5e9b0472-152c-45f9-853d-116aa434be22.gif)

3)**Страшные вещи тут происходят.** 

![header2](https://user-images.githubusercontent.com/90761929/135070594-d6f42177-8daa-47c8-869e-cfd60682ccb7.gif)

### Checkbox

Для чекбоксов JS не нужен. Это же касается toggle.

**Comment by Rizarid** [comment]
Исправил

**Comment by FanManutd** [comment]
### Subscription

Для `subscription-text-field` тоже нужно добавить `hover`и `focus`
![image](https://user-images.githubusercontent.com/90761929/135857044-b61ed5c5-04bb-481f-b7de-86a6f294ac9b.png)
