### ISSUE TITLE
Perfect Pixel

### ISSUE THREAD

**Issue by FanManutd** [Rizarid/apartmen-seach#7]
Добавь пожалуйста в репо скрины по которым ты сверял PerfectPixel

Есть явные несоответствия макету. У чекбоксов border-radius другой. Календарь и dropdown-ы не соответствуют. 
![image](https://user-images.githubusercontent.com/90761929/135068762-53ac61bb-10ee-471d-8c75-38d5229c6e5f.png)

### Иконки

Почему бы не вытащить из макета иконки в формате SVG? Не будет пикселей)
![image](https://user-images.githubusercontent.com/90761929/135069223-b2489e2b-8fed-4653-b758-d6d7131dbaee.png)
![image](https://user-images.githubusercontent.com/90761929/135069253-f41e52b8-f364-4fab-9347-62249cacb858.png)

**Comment by Rizarid** [comment]
Исправил

**Comment by FanManutd** [comment]
Внешний вид маленького календаря почему-то отличается. 
![image](https://user-images.githubusercontent.com/90761929/135464966-f158703b-0b64-4808-81fe-da6be8eea151.png)

**Update**
Я заметил, что на странице elements внешний вид один, а например на странице cards внешний вид календаря другой.
